repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
    -   id: pylint
